/* Generated By:JavaCC: Do not edit this line. SyntaTrialConstants.java */
package eurogate.pvl.regexp.request;

public interface SyntaTrialConstants {

  int EOF = 0;
  int ASSIGN = 5;
  int SEMICOLON = 6;
  int ANYNAME = 7;
  int NAME = 8;
  int FLOAT = 9;
  int INTEGER = 10;
  int ZEROINT = 11;
  int OCTINTEGER = 12;
  int HEXINTEGER = 13;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"=\"",
    "\";\"",
    "<ANYNAME>",
    "<NAME>",
    "<FLOAT>",
    "<INTEGER>",
    "\"0\"",
    "<OCTINTEGER>",
    "<HEXINTEGER>",
  };

}
