/* Generated By:JavaCC: Do not edit this line. TreeCutConstants.java */
package eurogate.pvl.regexp.drive;

public interface TreeCutConstants {

  int EOF = 0;
  int AND = 5;
  int OR = 6;
  int PLUS = 7;
  int MINUS = 8;
  int MULT = 9;
  int DIV = 10;
  int GE = 11;
  int LE = 12;
  int EQ = 13;
  int NE = 14;
  int GT = 15;
  int LT = 16;
  int NOT = 17;
  int LPAR = 18;
  int RPAR = 19;
  int NAME = 20;
  int ANYNAME = 21;
  int FLOAT = 22;
  int INTEGER = 23;
  int ZEROINT = 24;
  int OCTINTEGER = 25;
  int HEXINTEGER = 26;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"&&\"",
    "\"||\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "<NAME>",
    "<ANYNAME>",
    "<FLOAT>",
    "<INTEGER>",
    "\"0\"",
    "<OCTINTEGER>",
    "<HEXINTEGER>",
  };

}
